// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using kolokwium_s22006.Models;

namespace kolokwium_s22006.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("kolokwiumEF.Models.MusicLabel", b =>
                {
                    b.Property<int>("IdMusicLabel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMusicLabel");

                    b.ToTable("MusicLabel");

                    b.HasData(
                        new
                        {
                            IdMusicLabel = 1,
                            Name = "Label nr 1"
                        },
                        new
                        {
                            IdMusicLabel = 2,
                            Name = "Label nr 2"
                        },
                        new
                        {
                            IdMusicLabel = 3,
                            Name = "Label nr 3"
                        });
                });

            modelBuilder.Entity("kolokwiumEF.Models.Musician", b =>
                {
                    b.Property<int>("IdMusician")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nickname")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdMusician");

                    b.ToTable("Musician");

                    b.HasData(
                        new
                        {
                            IdMusician = 1,
                            FirstName = "Adam",
                            LastName = "Nowak",
                            Nickname = "Nowaczek"
                        },
                        new
                        {
                            IdMusician = 2,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            Nickname = "Kowal"
                        },
                        new
                        {
                            IdMusician = 3,
                            FirstName = "Anna",
                            LastName = "Szymanska",
                            Nickname = "Szyma"
                        });
                });

            modelBuilder.Entity("kolokwiumEF.Models.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("PublishDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<int>("IdMusicLabel")
                        .HasColumnType("int");

                    b.HasKey("IdAlbum");

                    b.HasIndex("IdMusicLabel");

                    b.ToTable("Album");

                    b.HasData(
                        new
                        {
                            IdAlbum = 1,
                            AlbumName = "Album nr 1",
                            PublishDate = DateTime.Parse("2022-06-02"),
                            IdMusicLabel = 1,
                        },
                        new
                        {
                            IdAlbum = 2,
                            AlbumName = "Album nr 2",
                            PublishDate = DateTime.Parse("2021-10-07"),
                            IdMusicLabel = 2
                        },
                        new
                        {
                            IdAlbum = 3,
                            AlbumName = "Album nr 3",
                            PublishDate = DateTime.Parse("2021-01-05"),
                            IdMusicLabel = 3
                        });
                });

            modelBuilder.Entity("kolokwiumEF.Models.Track", b =>
            {
                b.Property<int>("IdTrack")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("TrackName")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<float>("Duration")
                    .HasColumnType("int")
                    .IsRequired();

                b.Property<int>("IdMusicAlbum")
                    .HasColumnType("int");

                b.HasKey("IdTrack");

                b.HasIndex("IdMusicAlbum");

                b.ToTable("Track");

                b.HasData(
                    new
                    {
                        IdTrack = 1,
                        TrackName = "Track nr 1",
                        Duration = 90,
                        IdMusicAlbum = 1
                    },
                    new
                    {
                        IdTrack = 2,
                        TrackName = "Track nr 2",
                        Duration = 67,
                        IdMusicAlbum = 2
                    },
                    new
                    {
                        IdTrack = 3,
                        TrackName = "Track nr 3",
                        Duration = 58,
                        IdMusicAlbum = 3
                    });
            });

            modelBuilder.Entity("kolokwiumEF.Models.Musician_Track", b =>
                {
                    b.Property<int>("IdMusician")
                        .HasColumnType("int");

                    b.Property<int>("IdTrack")
                        .HasColumnType("int");

                    b.HasKey("IdMusician", "IdTrack");

                    b.HasIndex("IdTrack");

                    b.ToTable("Musician_Track");

                    b.HasData(
                        new
                        {
                            IdMusician = 1,
                            IdTrack = 1
                        },
                        new
                        {
                            IdMusician = 2,
                            IdTrack = 2
                        },
                        new
                        {
                            IdMusician = 3,
                            IdTrack = 3
                        });
                });

            modelBuilder.Entity("kolokwiumEF.Models.Track", b =>
                {
                    b.HasOne("kolokwiumEF.Models.Album", "Album")
                        .WithMany("Track")
                        .HasForeignKey("IdMusicAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("kolokwiumEF.Models.Album", b =>
            {
                b.HasOne("kolokwiumEF.Models.MusicLabel", "MusicLabel")
                    .WithMany("Album")
                    .HasForeignKey("IdMusicLabel")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("MusicLabel");
            });

            modelBuilder.Entity("kolokwiumEF.Models.Musician_Track", b =>
                {
                    b.HasOne("kolokwiumEF.Models.Musician", "Musician")
                        .WithMany("Musician_Track")
                        .HasForeignKey("IdMusician")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("kolokwiumEF.Models.Track", "Track")
                        .WithMany("Musician_Track")
                        .HasForeignKey("IdTrack")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Musician");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("kolokwiumEF.Models.MusicLabel", b =>
                {
                    b.Navigation("Album");
                });

            modelBuilder.Entity("kolokwiumEF.Models.Musician", b =>
                {
                    b.Navigation("Musician_Track");
                });

#pragma warning restore 612, 618
        }
    }
}
